Bump clamav version
alphagov/notifications-antivirus pull request #70
Opened 2021-04-20 10:45 UTC by idavidmcdonald

Brings it up to the latest stable version

Doesn't appear to be anything here that would be breaking changes for us
https://blog.clamav.net/2020/08/clamav-01030-release-candidate.html

---

🚨⚠️ This will be deployed automatically all the way to production when you click merge ⚠️🚨

For more information, including how to check this deployment on preview or staging first before it goes to production, see our [team wiki section on continuous deployment](https://github.com/alphagov/notifications-manuals/wiki/Deploying-with-concourse#continuous-deployment)

2021-04-20 16:49 UTC, benthorner approved these changes
Agree there doesn't look like there are any breaking changes.

2021-04-20 16:54 UTC, leohemsted requested changes
```
E: Version '0.103.2*' for 'clamav-daemon' was not found
E: Version '0.103.2*' for 'clamav-freshclam' was not found
```

not found in concourse. Might need to double check package sources etc. ugh.

2021-04-22 09:29 UTC, idavidmcdonald commented
So if I do

```
docker pull python:3.6-slim
docker run -it 5e900d21ca3f bash
apt-get update

apt list -a clamav-daemon
Listing... Done
clamav-daemon/stable 0.102.4+dfsg-0+deb10u1 amd64
clamav-daemon/stable-updates 0.102.3+dfsg-0+deb10u1 amd64

root@086b85333ff1:/# apt list -a clamav-freshclam
Listing... Done
clamav-freshclam/stable 0.102.4+dfsg-0+deb10u1 amd64
clamav-freshclam/stable-updates 0.102.3+dfsg-0+deb10u1 amd64
```

So it looks like the latest version of both freshclam and the daemon is 0.102.3. 

Bit surprised that 0.103.x isn't available yet to download for ubuntu given that 0.103.0 was released over 6 months ago (https://blog.clamav.net/2020/09/clamav-01030-released.html)

Maybe I'm just missing something about ubuntu package management but it looks like at the moment at least, it isn't possible to upgrade the version of clamav any higher so therefore I'll close this

2021-04-27 12:52 UTC, leohemsted approved these changes

2021-04-27 12:52 UTC, merged